--1). Which product category has the highest rating?
select product_category,max(rating) as highest_rating_by_category
from `amazon_sales_dataset (1)`
group by product_category;

-- 2).how many quantity_sold by customer_region?
SELECT customer_region,sum(quantity_sold) as total_quantity
from `amazon_sales_dataset (1)`
group by customer_region;

--3). Which payment method is most frequently used by customers in each region?
SELECT customer_region , max(payment_method) as highest_paymentmode_by_region
from `amazon_sales_dataset (1)`
group by customer_region;

-- 4).What is the total revenue generated by each customer region?
SELECT customer_region , sum(total_revenue) as total_revenue
from `amazon_sales_dataset (1)`
group by customer_region;

--5). What is the total discounted price for each product category?
SELECT product_category,sum(discounted_price) as total_disocunted_price
from `amazon_sales_dataset (1)`
group by product_category;

--6). Which are the top 5 customer regions with the highest ratings?
SELECT customer_region,MAX(rating) as highest_rating_by_region
from `amazon_sales_dataset (1)` 
group by customer_region
limit 5;

--7). What is the total quantity sold for Beauty products?
select product_category,sum(quantity_sold) as total_quantity_sold
from `amazon_sales_dataset (1)`
where product_category = 'beauty'
group by product_category;
-- 8).Which payment method (Cash on Delivery, Wallet, Debit Card, or UPI) is most used by customer_region
SELECT distinct(customer_region),payment_method as usage_count
from `amazon_sales_dataset (1)`
group by customer_region , payment_method;

--9). What is the average quantity_sold per order_date?
SELECT order_date, AVG(quantity_sold) AS avg_quantity
FROM `amazon_sales_dataset (1)`
GROUP BY order_date
ORDER BY avg_quantity DESC
LIMIT 1;

--10). On which order date was the highest quantity sold?
SELECT order_date, quantity_sold
FROM `amazon_sales_dataset (1)`
ORDER BY quantity_sold DESC
LIMIT 1;

--11). What is the highest rating given by customers in each region?
SELECT customer_region,max(rating)
from `amazon_sales_dataset (1)`
group by customer_region;

select * from `amazon_sales_dataset (1)`;
select * from `amazon_sales_dataset (1)`;
